services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=3000
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app:delegated
    environment:
      - FLASK_DEBUG=1

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data:
